force-app/main/default/objects/Field_History__c/Field_History__c.object-meta.xml
<CustomObject>
    <description>Identifies a change made to a field</description>
    <label>Field History</label>
    <nameField>
        <displayFormat>FH-{0000000}</displayFormat>
        <label>Field History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_History__c/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <description>API name of the field being changed</description>
    <label>Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History__c/fields/New_Value_Text__c.field-meta.xml
<CustomField>
    <fullName>New_Value_Text__c</fullName>
    <description>The new value of the field as plain text up to 255 characters</description>
    <label>New Value (Text)</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History__c/fields/Old_Value_Text__c.field-meta.xml
<CustomField>
    <fullName>Old_Value_Text__c</fullName>
    <description>The old value of the field as a plain text, up to 255 characters</description>
    <label>Old Value (Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HistorianTest.cls
@istest
public with sharing class HistorianTest {

	private static final String ACC_NAME_BEFORE = 'Test Account Insert Name';
	private static final String ACC_NAME_AFTER = 'Test Account Update Name';

	@isTest
	static void writeHistoryInsertTest() {
		Test.startTest();
		Account testAccount = new Account(Name = ACC_NAME_BEFORE);
		insert testAccount;
		Test.stopTest();
		List<Field_History__c> histories = [
				SELECT Id, New_Value_Text__c, Old_Value_Text__c, Field_API_Name__c
				FROM Field_History__c
		];
		Assert.areEqual(3, histories.size(), 'Wrong number of histories after account insert'); // Contains OwnerId and CleanStatus, too
		Field_History__c nameHistory = getNameHistory(histories);
		Assert.isNotNull(nameHistory, 'No history created for the name field on insert');
		Assert.areEqual(null, nameHistory.Old_Value_Text__c, 'Wrong OLD value for acc name change history on insert');
		Assert.areEqual(ACC_NAME_BEFORE, nameHistory.New_Value_Text__c, 'Wrong NEW value for acc name change history');
	}

	@isTest
	static void writeHistoryUpdateTest() {
		Account testAccount = new Account(Name = ACC_NAME_BEFORE);
		insert testAccount;
		Assert.areEqual(3, [SELECT count(Id) c FROM Field_History__c][0].get('c'), 'Wrong number of histories after account insert'); // Contains OwnerId and CleanStatus, too
		Test.startTest();
		testAccount.Name = ACC_NAME_AFTER;
		update testAccount;
		Test.stopTest();
		List<Field_History__c> histories = [
				SELECT Id, New_Value_Text__c, Old_Value_Text__c, Field_API_Name__c
				FROM Field_History__c
				ORDER BY Name DESC
		];
		Field_History__c nameHistory = getNameHistory(histories);
		Assert.isNotNull(nameHistory, 'No history created for the name field on insert');
		Assert.areEqual(ACC_NAME_BEFORE, nameHistory.Old_Value_Text__c, 'Wrong OLD value for acc name change history after update');
		Assert.areEqual(ACC_NAME_AFTER, nameHistory.New_Value_Text__c, 'Wrong NEW value for acc name change history after update');
	}

	/**
	* Helper to get the name field history from among other histories
	*/
	private static Field_History__c getNameHistory(List<Field_History__c> histories) {
		Field_History__c nameHistory;
		for (Field_History__c history : histories) {
			if (history.Field_API_Name__c == 'Name') {
				nameHistory = history;
				break;
			}
		}
		return nameHistory;
	}
}