force-app/main/default/objects/Field_History__c/Field_History__c.object-meta.xml
<CustomObject>
    <description>Identifies a change made to a field</description>
    <label>Field History</label>
    <nameField>
        <displayFormat>FH-{0000000}</displayFormat>
        <label>Field History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_History__c/fields/Change_Time__c.field-meta.xml
<CustomField>
    <fullName>Change_Time__c</fullName>
    <description>The time and date when the change was made</description>
    <label>Change Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Field_History__c/fields/Change_User__c.field-meta.xml
<CustomField>
    <fullName>Change_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user who made the change</description>
    <label>Change User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Field_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_History__c/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <description>API name of the field being changed</description>
    <label>Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History__c/fields/New_Value_Text__c.field-meta.xml
<CustomField>
    <fullName>New_Value_Text__c</fullName>
    <description>The new value of the field as plain text up to 255 characters</description>
    <label>New Value (Text)</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History__c/fields/Old_Value_Text__c.field-meta.xml
<CustomField>
    <fullName>Old_Value_Text__c</fullName>
    <description>The old value of the field as a plain text, up to 255 characters</description>
    <label>Old Value (Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>The Salesforce ID of the SObject record that was changed. This is a text pseudo-ID in order to support polymorphism.</description>
    <label>Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History__c/fields/Sobject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Sobject_API_Name__c</fullName>
    <description>The namespace-qualified API name of the SObject that was changed</description>
    <label>SObject API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Historian.cls
public with sharing class Historian {

	/**
	 * Helper signature that assumes it's being given the Trigger.newMap from an insert trigger
	 */
	public static void writeHistory(Map<Id, SObject> triggerNewMap) {
		Map<Id, SObject> triggerOldMap = new Map<Id, SObject>();
		writeHistory(triggerOldMap, triggerNewMap);
	}

	/**
	* Create a Field_History__c record for each updateable field changed among given records
	*/
	public static void writeHistory(Map<Id, SObject> triggerOldMap, Map<Id, SObject> triggerNewMap) {

		// Just a quick POC version of this code. Should really work for multiple SObject types
		List<String> updateableFields;
		if (triggerNewMap == null || triggerNewMap.isEmpty()) {
			return;
		} else {
			updateableFields = getUpdateableFields(triggerNewMap.values()[0].Id);
		}

		// Check what fields are changed and create a history record for each
		List<Field_History__c> fieldHistoriesForInsert = new List<Field_History__c>();
		for (Id recordId : triggerNewMap.keySet()) {
			SObject oldRecord = triggerOldMap.get(recordId);
			SObject newRecord = triggerNewMap.get(recordId);
			for (String field : updateableFields) {
				if (
						(oldRecord == null && newRecord.get(field) != null)
						|| (oldRecord != null && oldRecord.get(field) != newRecord.get(field))
				) {
					fieldHistoriesForInsert.add(generateFieldHistory(oldRecord, newRecord, field));
				}
			}
		}

		insert fieldHistoriesForInsert;
	}

	/**
	 * Schema-helper method. Gets all updateable fields for an SObject from a given record ID
	 */
	public static List<String> getUpdateableFields(Id recordId) {
		List<String> fieldApiNames = new List<String>();
		Schema.SObjectType sObjectType = recordId.getSObjectType();
		Schema.DescribeSObjectResult describeResult = sObjectType.getDescribe();
		Map<String, Schema.SObjectField> fieldsMap = describeResult.fields.getMap();
		for (Schema.SObjectField sObjectField: fieldsMap.values()) {
			DescribeFieldResult fieldDescribe = sObjectField.getDescribe();
			if (fieldDescribe.isUpdateable()) {
				fieldApiNames.add(fieldDescribe.getLocalName());
			}
		}
		return fieldApiNames;
	}

	/**
	 * Create a Field_History__c record from given old/new record and a field that we know has changed
	 */
	public static Field_History__c generateFieldHistory(SObject oldRecord, SObject newRecord, String fieldApiName) {
		String newValueString = newRecord.get(fieldApiName) == null ? '' : String.valueOf(newRecord.get(fieldApiName));
		if (newValueString.length() > 255) {
			newValueString = newValueString.substring(0, 255);
		}
		String oldValueString = '';
		if (oldRecord != null) {
			oldValueString = oldRecord.get(fieldApiName) == null ? '' : String.valueOf(oldRecord.get(fieldApiName));
			if (oldValueString.length() > 255) {
				oldValueString = oldValueString.substring(0, 255);
			}
		}

		Field_History__c newFieldHistoryRecord = new Field_History__c(
			Change_Time__c = System.now(),
			Change_User__c = Userinfo.getUserId(),
			Field_API_Name__c = fieldApiName,
			New_Value_Text__c = newValueString,
			Old_Value_Text__c = oldValueString,
			Record_Id__c = newRecord.Id,
			Sobject_Api_Name__c = newRecord.Id.getSObjectType().getDescribe().getLocalName()
		);
		return newFieldHistoryRecord;
	}

}